name: Docker Build & Deploy

on:
  push:
    branches:
      - main  # Runs workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use Ubuntu virtual machine for the pipeline

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fernando-posture-checker:${{ github.sha }} .

      # Step 4: Log in to Docker Hub (or AWS ECR if using that)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secret

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fernando-posture-checker:${{ github.sha }}

      # Step 6: Deploy Docker Container to EC2
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: "ec2-user"  # Adjust if you're using a different username
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST <<EOF
            # Pull the Docker image on the EC2 instance
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fernando-posture-checker:${{ github.sha }}
            
            # Run the Docker container (assuming port 80 is open on your EC2)
            sudo docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/fernando-posture-checker:${{ github.sha }}
          EOF
